# Generated by Django 4.0 on 2023-11-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkspace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='models_app.user', verbose_name='Пользователь'),
        ),
    ]
