# Generated by Django 4.0 on 2023-11-13 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_userworkspace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkspace',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='models_app.workspace', verbose_name='Рабочее пространство'),
        ),
    ]
