# Generated by Django 4.0 on 2023-11-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_alter_userworkspace_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='about',
            field=models.TextField(default=1, verbose_name='Чем занимается'),
            preserve_default=False,
        ),
    ]
