# Generated by Django 4.0 on 2023-12-08 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_workspace_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_messages', to='models_app.workspace', verbose_name='Сообшение рабочего пространства'),
            preserve_default=False,
        ),
    ]
