# Generated by Django 4.0 on 2023-12-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_message_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
